targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          # Uncomment to skip generating `copyWith` methods
          # copy_with: false
          # Uncomment to generate `fromJson` methods with JSON serialization
          json_serializable: true
          # Uncomment to generate `toString` methods
          # to_string: false
          # Uncomment to generate `==` and `hashCode` methods
          # equal: false
          # Uncomment to generate `toJson` methods
          # to_json: false
      riverpod_generator:
        enabled: true
      json_serializable:
        enabled: true
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
